from __future__ import annotations

from .application import (
    Course,
    CourseIDs,
    CourseNameUpdated,
    CourseNames,
    CoursePlacesUpdated,
    CourseRegistered,
    EnrolmentWithVerticalSlices,
    RegisterCourse,
    RegisterStudent,
    Student,
    StudentJoinedCourse,
    StudentJoinsCourse,
    StudentLeftCourse,
    StudentLeavesCourse,
    StudentMaxCoursesUpdated,
    StudentNameUpdated,
    StudentNames,
    StudentRegistered,
    StudentsIDs,
    UpdateCourseName,
    UpdateMaxCourses,
    UpdatePlaces,
    UpdateStudentName,
)

__all__ = [
    "Course",
    "CourseIDs",
    "CourseNameUpdated",
    "CourseNames",
    "CoursePlacesUpdated",
    "CourseRegistered",
    "EnrolmentWithVerticalSlices",
    "RegisterCourse",
    "RegisterStudent",
    "Student",
    "StudentJoinedCourse",
    "StudentJoinsCourse",
    "StudentLeftCourse",
    "StudentLeavesCourse",
    "StudentMaxCoursesUpdated",
    "StudentNameUpdated",
    "StudentNames",
    "StudentRegistered",
    "StudentsIDs",
    "UpdateCourseName",
    "UpdateMaxCourses",
    "UpdatePlaces",
    "UpdateStudentName",
]
